[package]
name = "pear-host"
version = "0.1.0"
edition = "2024"

[dependencies]
block2 = "0.6.2"
clap = { version = "4.6.6", features = ["derive"] }
dispatch2 = "0.3.1"
objc2 = "0.6.4"
objc2-foundation = { version = "0.3.2", features = ["NSURL", "NSString", "NSFileHandle", "NSArray", "NSError"] }
objc2-virtualization = "0.3.2"
